name: podnotes
description: Privacy preserving note taking app using PODs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.10
  markdown_editor_plus: ^0.2.13
  universal_io: ^2.2.2
  window_manager: ^0.3.5
  url_launcher: ^6.0.10
  jwt_decoder: ^2.0.1
  intl: ^0.18.0
  dart_jsonwebtoken: ^2.3.2
  fast_rsa: ^3.4.7
  solid_auth: ^0.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
