name: podnotes
description: Privacy preserving note taking app using PODs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #flutter_markdown: ^0.6.18+2
  markdown_editor_plus: ^0.2.13
  universal_io: ^2.2.2
  window_manager: ^0.3.5
  url_launcher: ^6.0.10
  jwt_decoder: ^2.0.1
  intl: ^0.18.0
  dart_jsonwebtoken: ^2.3.2
  fast_rsa: ^3.4.7
  solid_auth: ^0.1.12
  solid_encrypt: ^0.1.9
  openid_client: ^0.4.8
  rdflib: ^0.2.4
  crypto: ^3.0.3
  encrypt: ^5.0.3
  http: ^1.1.0

  # Form builder
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0

  # handle SVGs for Android, iOS, and Web.
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/types/
